spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        id:
          new_generator_mappings: false
        jdbc:
          batch_size: 20
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:voting
    username: sa
    password:
  h2:
    console:
      enabled: true
  data.rest:
    basePath: /api
    return-body-on-create: true
    default-page-size: 20
  server.servlet:
    encoding:
      charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
      enabled: true # Enable http encoding support
      force: true